name: publish-docs

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
  pull_request:
    branches:
      - 'main'

env:
  node-version: 14.x
  python-version: 3.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Cypress run
        uses: cypress-io/github-action@31b3f686c1ee05fb7390cc106d1f09eb83919a3c # tag=v3.2.0
        with:
          spec: cypress/integration/sample.spec.ts
          start: mkdocs serve
          wait-on: 'http://127.0.0.1:8000/'
          # we have already installed all dependencies above
          install: false
        timeout-minutes: 3
